#project_website_homepage:
#   pattern:  /hello/{name}
#   defaults: { _controller: ProjectWebsiteBundle:Default:index }

ProjectWebsiteBundle_homepage:
    pattern:  /
    defaults: { _controller: ProjectWebsiteBundle:Default:index }
    requirements:
        _method:  GET