parameters:
#    project_website.example.class: Project\WebsiteBundle\Example

services:
#    project_website.example:
#        class: %project_website.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
